[tool.poetry]
name = "pytest-reporter-plus"
version = "0.1.7"
description = "Lightweight enhanced HTML reporter for Pytest"
readme = "README.md"
authors = ["Emjey","Karan"]
license = "MIT"
packages = [{ include = "pytest_reporter_plus" }]

[tool.poetry.dependencies]
python = ">=3.9"
yagmail = ">=0.15.293,<0.16.0"
keyring = ">=25.6.0,<26.0.0"

[tool.poetry.dev-dependencies]
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
playwright ="^1.42.0"
pytest-playwright ="^0.4.3"
pytest-xdist = "^3.7.0"

[tool.poetry.group.dev.dependencies]
pytest-rerunfailures = "^15.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."pytest11"]
pytest_reporter_plus = "pytest_reporter_plus.plugin"


